<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="INLEN8520075951"><DocLocation><![CDATA[C:\UFT_Learning\DemoWebShopHybrid\TestCases\call_to_copy_action_demo1]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[call_to_copy_action_demo1]]></DName>
<Res><![CDATA[Res3]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Action rID="T5">
<AName><![CDATA[Copy of login]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:44]]></Time>
<TimeTick>1682579264</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:44]]></Time>
<TimeTick>1682579264</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" Source="Copy of login" SourceLine="0" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["644a12d994aaa23f195c"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:44]]></Time>
<TimeTick>1682579264</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" Source="Copy of login" SourceLine="1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:45]]></Time>
<TimeTick>1682579265</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Copy of login" SourceLine="2" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="Copy of login" SourceLine="0" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="27-04-2023 - 12:37:44" eTime="27-04-2023 - 12:37:45" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" >
<Disp><![CDATA[Copy of login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T10">
<AName><![CDATA[Copy of searchFlight]]></AName>
<AIter rID="T11" iterID="1" isCountable="False" >
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:45]]></Time>
<TimeTick>1682579265</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:45]]></Time>
<TimeTick>1682579265</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" Source="Copy of searchFlight" SourceLine="0" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:45]]></Time>
<TimeTick>1682579265</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" Source="Copy of searchFlight" SourceLine="1" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["First"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:46]]></Time>
<TimeTick>1682579266</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" Source="Copy of searchFlight" SourceLine="2" >
<Disp><![CDATA[Class.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["2"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:46]]></Time>
<TimeTick>1682579266</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="27" Source="Copy of searchFlight" SourceLine="3" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:46]]></Time>
<TimeTick>1682579266</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="29" Source="Copy of searchFlight" SourceLine="4" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 4]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:46]]></Time>
<TimeTick>1682579266</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="31" Source="Copy of searchFlight" SourceLine="5" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:46]]></Time>
<TimeTick>1682579266</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="33" Source="Copy of searchFlight" SourceLine="6" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Sanket"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:47]]></Time>
<TimeTick>1682579267</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="35" Source="Copy of searchFlight" SourceLine="7" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:47]]></Time>
<TimeTick>1682579267</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="37" Source="Copy of searchFlight" SourceLine="8" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:47]]></Time>
<TimeTick>1682579267</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="39" Source="Copy of searchFlight" SourceLine="9" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="20" Source="Copy of searchFlight" SourceLine="0" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="18" >
<Disp><![CDATA[Copy of searchFlight Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T23" iterID="2" isCountable="False" >
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:47]]></Time>
<TimeTick>1682579267</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:47]]></Time>
<TimeTick>1682579267</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="44" Source="Copy of searchFlight" SourceLine="0" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:48]]></Time>
<TimeTick>1682579268</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="46" Source="Copy of searchFlight" SourceLine="1" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["First"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:48]]></Time>
<TimeTick>1682579268</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="48" Source="Copy of searchFlight" SourceLine="2" >
<Disp><![CDATA[Class.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["2"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:48]]></Time>
<TimeTick>1682579268</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="50" Source="Copy of searchFlight" SourceLine="3" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:49]]></Time>
<TimeTick>1682579269</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="52" Source="Copy of searchFlight" SourceLine="4" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 4]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:49]]></Time>
<TimeTick>1682579269</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="54" Source="Copy of searchFlight" SourceLine="5" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:49]]></Time>
<TimeTick>1682579269</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="56" Source="Copy of searchFlight" SourceLine="6" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["darshan"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:49]]></Time>
<TimeTick>1682579269</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="58" Source="Copy of searchFlight" SourceLine="7" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:49]]></Time>
<TimeTick>1682579269</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="60" Source="Copy of searchFlight" SourceLine="8" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:49]]></Time>
<TimeTick>1682579269</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="62" Source="Copy of searchFlight" SourceLine="9" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="43" Source="Copy of searchFlight" SourceLine="0" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="41" >
<Disp><![CDATA[Copy of searchFlight Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T35" iterID="3" isCountable="False" >
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:50]]></Time>
<TimeTick>1682579270</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:50]]></Time>
<TimeTick>1682579270</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="67" Source="Copy of searchFlight" SourceLine="0" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:50]]></Time>
<TimeTick>1682579270</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="69" Source="Copy of searchFlight" SourceLine="1" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["First"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:50]]></Time>
<TimeTick>1682579270</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="71" Source="Copy of searchFlight" SourceLine="2" >
<Disp><![CDATA[Class.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["2"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:51]]></Time>
<TimeTick>1682579271</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="73" Source="Copy of searchFlight" SourceLine="3" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:51]]></Time>
<TimeTick>1682579271</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="75" Source="Copy of searchFlight" SourceLine="4" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 4]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:51]]></Time>
<TimeTick>1682579271</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="77" Source="Copy of searchFlight" SourceLine="5" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:51]]></Time>
<TimeTick>1682579271</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="79" Source="Copy of searchFlight" SourceLine="6" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Kiran"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:51]]></Time>
<TimeTick>1682579271</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="81" Source="Copy of searchFlight" SourceLine="7" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:51]]></Time>
<TimeTick>1682579271</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="83" Source="Copy of searchFlight" SourceLine="8" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:52]]></Time>
<TimeTick>1682579272</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="85" Source="Copy of searchFlight" SourceLine="9" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="66" Source="Copy of searchFlight" SourceLine="0" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="64" >
<Disp><![CDATA[Copy of searchFlight Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</AIter>
<AIter rID="T47" iterID="4" isCountable="False" >
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:52]]></Time>
<TimeTick>1682579272</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[fromCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:52]]></Time>
<TimeTick>1682579272</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="90" Source="Copy of searchFlight" SourceLine="0" >
<Disp><![CDATA[fromCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[toCity.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:52]]></Time>
<TimeTick>1682579272</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="92" Source="Copy of searchFlight" SourceLine="1" >
<Disp><![CDATA[toCity.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Class.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["First"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:52]]></Time>
<TimeTick>1682579272</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="94" Source="Copy of searchFlight" SourceLine="2" >
<Disp><![CDATA[Class.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[numOfTickets.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["2"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:53]]></Time>
<TimeTick>1682579273</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="96" Source="Copy of searchFlight" SourceLine="3" >
<Disp><![CDATA[numOfTickets.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:53]]></Time>
<TimeTick>1682579273</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="98" Source="Copy of searchFlight" SourceLine="4" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[0, 4]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:53]]></Time>
<TimeTick>1682579273</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="100" Source="Copy of searchFlight" SourceLine="5" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:53]]></Time>
<TimeTick>1682579273</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="102" Source="Copy of searchFlight" SourceLine="6" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Viranchi"]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:53]]></Time>
<TimeTick>1682579273</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="104" Source="Copy of searchFlight" SourceLine="7" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:54]]></Time>
<TimeTick>1682579274</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="106" Source="Copy of searchFlight" SourceLine="8" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:54]]></Time>
<TimeTick>1682579274</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="108" Source="Copy of searchFlight" SourceLine="9" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="89" Source="Copy of searchFlight" SourceLine="0" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="StartIteration" icon="3" nRep="87" >
<Disp><![CDATA[Copy of searchFlight Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</AIter>
<Summary sTime="27-04-2023 - 12:37:45" eTime="27-04-2023 - 12:37:54" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="17" >
<Disp><![CDATA[Copy of searchFlight Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T59">
<AName><![CDATA[Copy of logout]]></AName>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:54]]></Time>
<TimeTick>1682579274</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[27-04-2023 - 12:37:54]]></Time>
<TimeTick>1682579274</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="114" Source="Copy of logout" SourceLine="0" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="113" Source="Copy of logout" SourceLine="0" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="27-04-2023 - 12:37:54" eTime="27-04-2023 - 12:37:54" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="111" >
<Disp><![CDATA[Copy of logout Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="27-04-2023 - 12:37:43" eTime="27-04-2023 - 12:37:54" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[call_to_copy_action_demo1 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="27-04-2023 - 12:37:42" eTime="27-04-2023 - 12:37:54" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test call_to_copy_action_demo1 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>