<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="INLEN8520075951"><DocLocation><![CDATA[C:\UFT_Learning\DemoWebShopHybrid\TestCases\AddToCart]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[AddToCart]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
ActiveX, Java, Silverlight, WinForms.]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:24]]></Time>
<TimeTick>1682414844</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[cart]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:25]]></Time>
<TimeTick>1682414845</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:25]]></Time>
<TimeTick>1682414845</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:31]]></Time>
<TimeTick>1682414851</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:31]]></Time>
<TimeTick>1682414851</TimeTick>
<NodeArgs eType="User" icon="7" nRep="16" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:32]]></Time>
<TimeTick>1682414852</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:32]]></Time>
<TimeTick>1682414852</TimeTick>
<NodeArgs eType="User" icon="7" nRep="19" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman@Rahman.com"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:32]]></Time>
<TimeTick>1682414852</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Value - 'Rahman@Rahman.com' entered in Field - '[ Email ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:32]]></Time>
<TimeTick>1682414852</TimeTick>
<NodeArgs eType="User" icon="7" nRep="23" status="Passed" >
<Disp><![CDATA[Value - 'Rahman@Rahman.com' entered in Field - '[ Email ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:33]]></Time>
<TimeTick>1682414853</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:33]]></Time>
<TimeTick>1682414853</TimeTick>
<NodeArgs eType="User" icon="7" nRep="26" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rahman@12345"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:33]]></Time>
<TimeTick>1682414853</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="29" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:33]]></Time>
<TimeTick>1682414853</TimeTick>
<NodeArgs eType="User" icon="7" nRep="30" status="Passed" >
<Disp><![CDATA[Value - 'Rahman@12345' entered in Field - '[ Password ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:33]]></Time>
<TimeTick>1682414853</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="32" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:33]]></Time>
<TimeTick>1682414853</TimeTick>
<NodeArgs eType="User" icon="7" nRep="33" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:33]]></Time>
<TimeTick>1682414853</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="36" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:33]]></Time>
<TimeTick>1682414853</TimeTick>
<NodeArgs eType="User" icon="7" nRep="37" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ q ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:34]]></Time>
<TimeTick>1682414854</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="39" >
<Disp><![CDATA[[ q ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj ><![CDATA[Search field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:34]]></Time>
<TimeTick>1682414854</TimeTick>
<NodeArgs eType="User" icon="7" nRep="40" status="Passed" >
<Disp><![CDATA[Search field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ q ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["computer"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:35]]></Time>
<TimeTick>1682414855</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" >
<Disp><![CDATA[[ q ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[Value - 'computer' entered in Field - '[ q ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:35]]></Time>
<TimeTick>1682414855</TimeTick>
<NodeArgs eType="User" icon="7" nRep="44" status="Passed" >
<Disp><![CDATA[Value - 'computer' entered in Field - '[ q ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ Search ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:35]]></Time>
<TimeTick>1682414855</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" >
<Disp><![CDATA[[ Search ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[Search button is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:35]]></Time>
<TimeTick>1682414855</TimeTick>
<NodeArgs eType="User" icon="7" nRep="47" status="Passed" >
<Disp><![CDATA[Search button is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ Search ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebButton]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:35]]></Time>
<TimeTick>1682414855</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA["[ Search ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;disabled&quot; has the expected value: 0.]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:35]]></Time>
<TimeTick>1682414855</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="50" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Search ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="49" status="Passed" >
<Disp><![CDATA[[ Search ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ Search ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebButton]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:35]]></Time>
<TimeTick>1682414855</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA["[ Search ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;name&quot; has the expected value: &quot;Search&quot;.]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:35]]></Time>
<TimeTick>1682414855</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="53" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Search ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="52" status="Passed" >
<Disp><![CDATA[[ Search ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Search ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebButton]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:35]]></Time>
<TimeTick>1682414855</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA["[ Search ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:35]]></Time>
<TimeTick>1682414855</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="56" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Search ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="55" status="Passed" >
<Disp><![CDATA[[ Search ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:35]]></Time>
<TimeTick>1682414855</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="59" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA['[ Search ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:35]]></Time>
<TimeTick>1682414855</TimeTick>
<NodeArgs eType="User" icon="7" nRep="60" status="Passed" >
<Disp><![CDATA['[ Search ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ Build your own cheap computer ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:36]]></Time>
<TimeTick>1682414856</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="62" >
<Disp><![CDATA[[ Build your own cheap computer ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj ><![CDATA[Product link is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:36]]></Time>
<TimeTick>1682414856</TimeTick>
<NodeArgs eType="User" icon="7" nRep="63" status="Passed" >
<Disp><![CDATA[Product link is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ Build your own cheap computer ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:36]]></Time>
<TimeTick>1682414856</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="66" >
<Disp><![CDATA[[ Build your own cheap computer ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA['[ Build your own cheap computer ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:36]]></Time>
<TimeTick>1682414856</TimeTick>
<NodeArgs eType="User" icon="7" nRep="67" status="Passed" >
<Disp><![CDATA['[ Build your own cheap computer ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ product_attribute_72_5_18 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:41]]></Time>
<TimeTick>1682414861</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="69" >
<Disp><![CDATA[[ product_attribute_72_5_18 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[Processor Radio group is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:41]]></Time>
<TimeTick>1682414861</TimeTick>
<NodeArgs eType="User" icon="7" nRep="70" status="Passed" >
<Disp><![CDATA[Processor Radio group is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ product_attribute_72_5_18 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["52"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:42]]></Time>
<TimeTick>1682414862</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="73" >
<Disp><![CDATA[[ product_attribute_72_5_18 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj ><![CDATA[Value - '52' selected from Drop Down Field - '[ product_attribute_72_5_18 ] radio button group']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:42]]></Time>
<TimeTick>1682414862</TimeTick>
<NodeArgs eType="User" icon="7" nRep="74" status="Passed" >
<Disp><![CDATA[Value - '52' selected from Drop Down Field - '[ product_attribute_72_5_18 ] radio button group']]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ product_attribute_72_6_19 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:42]]></Time>
<TimeTick>1682414862</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="76" >
<Disp><![CDATA[[ product_attribute_72_6_19 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[RAM Radio group is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:42]]></Time>
<TimeTick>1682414862</TimeTick>
<NodeArgs eType="User" icon="7" nRep="77" status="Passed" >
<Disp><![CDATA[RAM Radio group is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ product_attribute_72_6_19 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["55"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:42]]></Time>
<TimeTick>1682414862</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="80" >
<Disp><![CDATA[[ product_attribute_72_6_19 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[Value - '55' selected from Drop Down Field - '[ product_attribute_72_6_19 ] radio button group']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:42]]></Time>
<TimeTick>1682414862</TimeTick>
<NodeArgs eType="User" icon="7" nRep="81" status="Passed" >
<Disp><![CDATA[Value - '55' selected from Drop Down Field - '[ product_attribute_72_6_19 ] radio button group']]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ addtocart_72.EnteredQuantity ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:42]]></Time>
<TimeTick>1682414862</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="83" >
<Disp><![CDATA[[ addtocart_72.EnteredQuantity ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[Quantity field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:42]]></Time>
<TimeTick>1682414862</TimeTick>
<NodeArgs eType="User" icon="7" nRep="84" status="Passed" >
<Disp><![CDATA[Quantity field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ addtocart_72.EnteredQuantity ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:42]]></Time>
<TimeTick>1682414862</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="87" >
<Disp><![CDATA[[ addtocart_72.EnteredQuantity ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[Value - '1' entered in Field - '[ addtocart_72.EnteredQuantity ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:42]]></Time>
<TimeTick>1682414862</TimeTick>
<NodeArgs eType="User" icon="7" nRep="88" status="Passed" >
<Disp><![CDATA[Value - '1' entered in Field - '[ addtocart_72.EnteredQuantity ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ product_attribute_72_3_20 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:42]]></Time>
<TimeTick>1682414862</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="90" >
<Disp><![CDATA[[ product_attribute_72_3_20 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj ><![CDATA[RAM Radio group is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:42]]></Time>
<TimeTick>1682414862</TimeTick>
<NodeArgs eType="User" icon="7" nRep="91" status="Passed" >
<Disp><![CDATA[RAM Radio group is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ product_attribute_72_3_20 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["58"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:43]]></Time>
<TimeTick>1682414863</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="94" >
<Disp><![CDATA[[ product_attribute_72_3_20 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj ><![CDATA[Value - '58' selected from Drop Down Field - '[ product_attribute_72_3_20 ] radio button group']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:43]]></Time>
<TimeTick>1682414863</TimeTick>
<NodeArgs eType="User" icon="7" nRep="95" status="Passed" >
<Disp><![CDATA[Value - '58' selected from Drop Down Field - '[ product_attribute_72_3_20 ] radio button group']]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ Add to cart ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:43]]></Time>
<TimeTick>1682414863</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="97" >
<Disp><![CDATA[[ Add to cart ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA[Add to cart button is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:43]]></Time>
<TimeTick>1682414863</TimeTick>
<NodeArgs eType="User" icon="7" nRep="98" status="Passed" >
<Disp><![CDATA[Add to cart button is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ Add to cart ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:43]]></Time>
<TimeTick>1682414863</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="101" >
<Disp><![CDATA[[ Add to cart ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA['[ Add to cart ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:43]]></Time>
<TimeTick>1682414863</TimeTick>
<NodeArgs eType="User" icon="7" nRep="102" status="Passed" >
<Disp><![CDATA['[ Add to cart ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj ><![CDATA[Product added successfully in the shopping cart]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:44]]></Time>
<TimeTick>1682414864</TimeTick>
<NodeArgs eType="User" icon="7" nRep="105" status="Passed" >
<Disp><![CDATA[Product added successfully in the shopping cart]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ Tricentis Demo Web Shop ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:44]]></Time>
<TimeTick>1682414864</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="108" >
<Disp><![CDATA[[ Tricentis Demo Web Shop ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ q ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:45]]></Time>
<TimeTick>1682414865</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="110" >
<Disp><![CDATA[[ q ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj ><![CDATA[Search field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:45]]></Time>
<TimeTick>1682414865</TimeTick>
<NodeArgs eType="User" icon="7" nRep="111" status="Passed" >
<Disp><![CDATA[Search field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ q ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Shoe"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:45]]></Time>
<TimeTick>1682414865</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="114" >
<Disp><![CDATA[[ q ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj ><![CDATA[Value - 'Shoe' entered in Field - '[ q ] edit box']]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:45]]></Time>
<TimeTick>1682414865</TimeTick>
<NodeArgs eType="User" icon="7" nRep="115" status="Passed" >
<Disp><![CDATA[Value - 'Shoe' entered in Field - '[ q ] edit box']]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ Search ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:45]]></Time>
<TimeTick>1682414865</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="117" >
<Disp><![CDATA[[ Search ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj ><![CDATA[Search button is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:45]]></Time>
<TimeTick>1682414865</TimeTick>
<NodeArgs eType="User" icon="7" nRep="118" status="Passed" >
<Disp><![CDATA[Search button is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ Search ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebButton]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:45]]></Time>
<TimeTick>1682414865</TimeTick>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA["[ Search ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;disabled&quot; has the expected value: 0.]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:45]]></Time>
<TimeTick>1682414865</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="121" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Search ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="120" status="Passed" >
<Disp><![CDATA[[ Search ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ Search ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebButton]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:45]]></Time>
<TimeTick>1682414865</TimeTick>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA["[ Search ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;name&quot; has the expected value: &quot;Search&quot;.]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:45]]></Time>
<TimeTick>1682414865</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="124" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Search ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="123" status="Passed" >
<Disp><![CDATA[[ Search ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ Search ]]]></Obj>
<Details plainTxt="False" ><![CDATA[WebButton]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:45]]></Time>
<TimeTick>1682414865</TimeTick>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA["[ Search ]"]]></Obj>
<Details plainTxt="False" ><![CDATA[Property &quot;visible&quot; has the expected value: True.]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:45]]></Time>
<TimeTick>1682414865</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="127" status="Passed" nType="CheckProperty" >
<Disp><![CDATA["[ Search ]"]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="126" status="Passed" >
<Disp><![CDATA[[ Search ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25-04-2023 - 14:57:46]]></Time>